#index:
#    path: /
#    controller: App\Controller\DefaultController::index

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

mentions_legales:
    path:         /mentions-legales
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: mentions.html.twig