fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

# admin:
#     path:         /admin
#     controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
#     name: app_admin
#     defaults:
#         template: admin/index.html.twig

mentions_legales:
    path:         /mentions-legales
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: mentions.html.twig