parameters:
doctrine:
    dbal:
        # change to env variables
        default_connection: mysql
        connections:
            nakaoni:
                # Change to env variables
                driver: 'pdo_mysql'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
                dbname:           nakaonicdpadmin
                user:             nakaonicdpadmin
                password:         Raptors0308
                host:             nakaonicdpadmin.mysql.db
                server_version:   5.6
            mysql:
                driver: 'pdo_mysql'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
                dbname:           '%env(DATABASE_NAME)%'
                user:             '%env(DATABASE_USER)%'
                password:         '%env(DATABASE_PASSWORD)%'
                host:             '%env(DATABASE_HOST)%'
                server_version:   5.6
            psql:
                driver: 'pdo_pgsql'
                dbname:           '%env(DATABASE_NAME)%'
                user:             '%env(DATABASE_USER)%'
                password:         '%env(DATABASE_PASSWORD)%'
                host:             '%env(DATABASE_HOST)%'
                server_version:   10.4

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
