fos_user:
    db_driver: orm
    firewall_name: main
    use_authentication_listener: true
    user_class: App\Entity\Utilisateur
    service:
        mailer: fos_user.mailer.twig_swift
    from_email:
        # change to env variables
        address: '%env(MAIL_SENDER)%'
        sender_name: Contact
    registration:
        form:
            type: App\Form\RegistrationType