framework:
    secret: '%env(APP_SECRET)%'
    default_locale: fr
    csrf_protection: true
    #http_method_override: true
    translator : { fallbacks: ['%locale%'] }

    session:
        handler_id: ~

    php_errors:
        log: true

    cache:
        # Redis
        #app: cache.adapter.redis
        #default_redis_provider: redis://localhost

    templating:
        engines:
            twig