security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
        
    role_hierarchy:
        ROLE_ABONNE: ROLE_USER
        ROLE_MODERATEUR: ROLE_ABONNE
        ROLE_AUTEUR: ROLE_MODERATEUR
        ROLE_ADMIN: ROLE_AUTEUR

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout: true
            anonymous: true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_partials, role: ROLE_MODERATEUR }
        - { path: ^/admin, role: ROLE_MODERATEUR }