swiftmailer:
    #url: '%env(MAILER_URL)%'
    #spool: { type: 'memory' }
    transport: "%mailer_transport%"
    encryption: "%mailer_encryption%"
    port:      "%mailer_port%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
