swiftmailer:
    #TODO: change to => url: '%env(MAILER_URL)%'
    transport: "%mailer_transport%"
    encryption: "%mailer_encryption%"
    port:      "%mailer_port%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
