# TODO remove bundle to do your own
vich_uploader:
    db_driver: orm

    mappings:
        articles_image:
            uri_prefix: /images/articles
            upload_destination: '%kernel.project_dir%/public/images/articles'
            namer: Vich\UploaderBundle\Naming\OrignameNamer

            inject_on_load: true
            delete_on_update: false
            delete_on_remove: true